# Generated by Django 5.2.7 on 2025-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geekmodels',
            name='address',
            field=models.TextField(default='None'),
        ),
    ]
